listener 1883
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl
persistence false
max_packet_size 2048
message_size_limit 1024
max_inflight_messages 16
max_queued_messages 64
log_dest stdout
